### ISSUE TITLE
Edit Reviews?

### ISSUE THREAD

**Issue by doabell** [Nicholas-Sliter/middcourses2#124]
Hi midd.dev, thank you for reviving this great project!

I accidentally chose a wrong option on a previous review, so could there be an edit button?
A delete button would also help, but I totally understand if not.

Thanks, and have a great day.

**Comment by Nicholas-Sliter** [comment]
Hi, both a delete and edit option are intended features but have not been developed yet.  I will keep you updated on their progress.  In the meantime, if you flag the review in question and add your intended edit in the "Other, please specify" textbox, I can manually adjust the review.

**Comment by doabell** [comment]
Thanks for the quick implementation!

**Comment by Nicholas-Sliter** [comment]
For future reference, a fix was implemented by adding an edit feature to user reviews on the [midd,courses/profile/reviews](midd,courses/profile/reviews) page.
