### ISSUE TITLE
Reviewed courses but still can't access the whole site

### ISSUE THREAD

**Issue by adilalvi11** [Nicholas-Sliter/middcourses2#280]
I've reviewed around 6-7 courses over the last 6 months, including one very recently, and I am still unable to access parts of the website. Every time I try to select a professor or a class, I get a pop-up that says I need to review at least two courses to gain access.

**Comment by Nicholas-Sliter** [comment]
This is likely due to your reviews being old. Since you already wrote 1 review recently, writing one more review should give you full access. If this does not resolve the issue please let me know and send my your Middlebury email address so I can troubleshoot.
